version: '3.8'

networks:
  mercado-livro:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}

services:

  db:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mercadolivro
    ports:
      - '5432:5432'

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - mercado-livro
    ports:
      - '9090:9090'
    restart: always

  grafana:
    image: grafana/grafana:latest
    networks:
      - mercado-livro
    ports:
      - '3000:3000'
    volumes:
      - ./observability/grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    restart: always