version: '3.8'

volumes:
  prometheus_data: {}
  grafana_data: {}
  fulfillment-service-data:

services:

  db:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mercadolivro
    ports:
      - '5432:5432'

  prometheus:
    image: prom/prometheus:v2.20.0
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus/crm-fulfillment-service
    ports:
      - '9190:9090'
    restart: always

  grafana:
    image: grafana/grafana:7.2.0
    ports:
      - '3010:3000'
    volumes:
      - ./observability/grafana:/etc/grafana/provising
      - grafana_data:/var/lib/grafana/card-invoice
    restart: always